### ISSUE TITLE
Set a cookie to remember visitor's display name across LightBlueTent

### ISSUE THREAD

**Issue by matiasilva** [SRCF/lightbluetent#11]
Add a ticky box to opt-in

**Comment by dnlburgess** [comment]
Do we still want to do this, or are we happy for the attendee to provide their desired name on a per-stall basis?

**Comment by matiasilva** [comment]
We agreed in a comment in #53 to not have this behavior. On second thought, I think it is useful behavior so long as we let them change their name if they want to, ie just pre fill it. Imagine an event hosted purely on LBT, and the person is going from society to society in our directory. It would be massively convenient for most to just have to type it in once.

**Comment by matiasilva** [comment]
Done with visitor permissions.
