### ISSUE TITLE
Notify of errors in production

### ISSUE THREAD

**Issue by sourtin** [SRCF/lightbluetent#127]
Errors in production should be emailed immediately to the maintainers, rather than waiting for the affected user to (hopefully) contact us asking for help.

**Comment by edwinbalani** [comment]
One approach, according to [this popular tutorial](https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-vii-error-handling/page/6), is to add an `SMTPHandler` from Python's `logging.handlers` module to the Flask logger (`app.logger`)
