### ISSUE TITLE
Allow for the creation of an admin stall

### ISSUE THREAD

**Issue by matiasilva** [SRCF/lightbluetent#14]
Similar to a "break room", this is a private room just for society admins.

**Comment by dalcde** [comment]
I'm not sure if we want to do this, if we are concerned about server load, especially if we envision a lot of society admins joining this room. Perhaps we could decide after sign ups.

**Comment by edwinbalani** [comment]
I suspect most socs will have their own existing back-channels for something like this.  Besides a generic videoconferencing option what value can we offer?

**Comment by matiasilva** [comment]
This is true, and I suspect they could just use timeout.srcf.
