### ISSUE TITLE
Replace manage.py with a Makefile

### ISSUE THREAD

**Issue by doismellburning** [SRCF/lightbluetent#32]
I'd like to propose replacing manage.py with a Makefile. I'm happy to do the work myself, but I'd like to discuss it and get approval from a project owner (@matiasilva ?) before I do the work.

My main reasons:

* Most of `manage.py` is calls to `subprocess` so a Makefile feels like a better fit
* Using a Makefile means you can start with it straight away (`manage.py` requires you to have installed all dependencies first)
* make has more appropriate default behaviours around subcommand failure  - right now e.g. we're accidentally not propagating the `pytest` exit code when doing `manage.py test` so `manage.py` still exits successfully despite test failure

I appreciate this is an opinionated tooling change, but I think it could help accessibility.

See https://github.com/doismellburning/emporium/blob/master/Makefile for an example

**Comment by doismellburning** [comment]
cc @edwinbalani and @CHTJonas per previous discussion

**Comment by matiasilva** [comment]
I think this is a good move for us. The manage.py file was kind of a hack and it does some odd things that I imported from a tutorial. I agree it's not optimal and it should be replaced with something better. You highlight good reasons for doing so, so a thumbs up from me!

**Comment by doismellburning** [comment]
@matiasilva Thanks. Is your approval sufficient here?

**Comment by matiasilva** [comment]
Is this still compatible with Flask? I don't see any reason why not. If it is, you have the OK from me to go ahead with this. Thanks again.

**Comment by matiasilva** [comment]
An update: we no longer use manage.py for anything and instead either run commands like `flask db migrate` using `pipenv shell` which loads in the env vars automatically or use direct docker compose calls.

**Comment by matiasilva** [comment]
Closed by #112
