### ISSUE TITLE
Convert all file extensions to lowercase when checking

### ISSUE THREAD

**Issue by matiasilva** [SRCF/lightbluetent#97]
We recently saw that JPG files could not be uploaded even though the file extension is supported. The reason is that we are not converting file extensions to lowercase when comparing.

**Comment by sourtin** [comment]
Extensions are no longer considered when checking if we support a supplied image, but we can and should change the saved extension to png in all cases as we are manipulating the image and adding an alpha channel.

**Comment by sourtin** [comment]
Also we could remove the check that the uploaded filename is not the empty string, as I'm not sure what benefit that has

**Comment by matiasilva** [comment]
The check for an empty file name is because a file object still appears in request.files even though no image was uploaded. I don't really know why.

**Comment by matiasilva** [comment]
@sourtin are you free to add png to the saved file?

**Comment by sourtin** [comment]
#118
